OpenStack-mobile/summit-app-ios

OpenStack Summit/CoreSummit/RealmSummitEvent.swift, OpenStack Summit/OpenStack Summit/Filter.swift, OpenStack Summit/OpenStack Summit/GeneralScheduleFilterViewController.swift, OpenStack Summit/OpenStack Summit/GeneralScheduleViewController.swift, OpenStack Summit/OpenStack Summit/LevelScheduleViewController.swift, OpenStack Summit/OpenStack Summit/TrackScheduleViewController.swift
Adds summit type and removes event type filtering.
=> [iOS] [11844] Adds summit type filtering.

OpenStack Summit/CoreSummit/FeedbackRequest.swift
Leaving feedback was failing for FeedbackVC.
=> [CoreSummit] [11880] fixed leaving feedback

OpenStack Summit/CoreSummit/RealmTicketType.swift, OpenStack Summit/CoreSummit/TicketType.swift, OpenStack Summit/CoreSummit/TicketTypeJSON.swift, OpenStack Summit/CoreSummitTests/StoreTests.swift
Fixed JSON parsing of `TicketType`.
=> [CoreSummit] [11942] fixed JSON parsing of TicketType

OpenStack Summit/CoreSummit/PresentationJSON.swift, OpenStack Summit/CoreSummit/RealmSummitEvent.swift, OpenStack Summit/OpenStack Summit/EventDetail.swift, OpenStack Summit/OpenStack Summit/EventDetailViewController.swift
Fixed moderators not showing in `EventDetailViewController`
=> [11944] Fixed moderators not showing

OpenStack Summit/CoreSummit/SummitRequest.swift, OpenStack Summit/OpenStack Summit.xcodeproj/project.pbxproj, OpenStack Summit/OpenStack Summit.xcodeproj/xcshareddata/xcschemes/OpenStack Summit Mocked.xcscheme, OpenStack Summit/OpenStack Summit/AppDelegate.swift
Under the mocked configuration, the JSON for the app will be mocked,
using the JSON we already have for the unit testing.
=> [11948] Added Mocked environment and target for external contributors

OpenStack Summit/CoreSummit/DataUpdate.swift, OpenStack Summit/CoreSummit/DataUpdatePoller.swift
Process the DataUpdates with Realm on a background thread.
=> [11991] Process DataUpdates on background thread

OpenStack Summit/OpenStack Summit/Info.plist, OpenStack Summit/OpenStackSummitWatch Extension/Info.plist, OpenStack Summit/OpenStackSummitWatch/Info.plist
=> Version bump to 2.0.5

OpenStack Summit/CoreSummit/DataUpdate.swift, OpenStack Summit/CoreSummit/DataUpdatePoller.swift
This reverts commit 5b40cc56877a73864a1dba07c74accc7b83b3458, reversing
changes made to c979bf7ffd402f7cf347f9727263f3b30cc4cc2f.
Causing Realm thread error.
=> Revert "Merge pull request #24 from OpenStack-mobile/feature/11991"

OpenStack Summit/OpenStack Summit/Info.plist, OpenStack Summit/OpenStackSummitWatch Extension/Info.plist, OpenStack Summit/OpenStackSummitWatch/Info.plist
Fixes crash issue with Realm threading.
=> Version bump to 2.0.7

OpenStack Summit/OpenStack Summit/EventDetail.swift, OpenStack Summit/OpenStackSummitWatch Extension/EventDetail.swift
Featured param is only intended for website usage .
If video present, show it .
=> [12023] Disregard featured filter for event videos

OpenStack Summit/OpenStack Summit/DataUpdatePoller.swift, OpenStack Summit/OpenStack Summit/Filter.swift, OpenStack Summit/OpenStack Summit/GeneralScheduleViewController.swift, OpenStack Summit/OpenStack Summit/PushNotificationManager.swift, OpenStack Summit/OpenStack Summit/ScheduleViewController.swift
`SummitManager` was added in https://github.com/OpenStack-mobile/summit-app-ios/commit/3514b6d77955e90a557915964c0479095165c6fe 
This fixes support for it in the iOS app.
=> [12139] Support for SummitManager

OpenStack Summit/CoreSummit/Store.swift, OpenStack Summit/OpenStack Summit/AppDelegate.swift, OpenStack Summit/OpenStack Summit/Menu.storyboard, OpenStack Summit/OpenStack Summit/MenuViewController.swift, OpenStack Summit/OpenStack Summit/Notifications.storyboard, OpenStack Summit/OpenStack Summit/NotificationsViewController.swift, OpenStack Summit/OpenStack Summit/PushNotificationManager.swift, OpenStack Summit/OpenStack Summit/SweetAlert.swift, OpenStack Summit/OpenStack Summit/TeamMessagesViewController.swift, OpenStack Summit/OpenStack Summit/Teams.storyboard, OpenStack Summit/OpenStack Summit/TeamsViewController.swift
- Add a message counter for new messages next to Inbox
- Add banner notification
=> [iOS] [12450] Added unread notifications counter

OpenStack Summit/OpenStack Summit/Store.swift, OpenStack Summit/OpenStackSummitWatch Extension/AboutInterfaceController.swift, OpenStack Summit/OpenStackSummitWatch Extension/MenuInterfaceController.swift
- Fixed clearing Summit cache
- Fixed Error message when loading summit
=> [watchOS] Cache and Error Handling Improvements

OpenStack Summit/CoreSummit/Event.swift, OpenStack Summit/CoreSummit/EventJSON.swift, OpenStack Summit/CoreSummit/EventManagedObject.swift, OpenStack Summit/CoreSummit/MemberRequest.swift, OpenStack Summit/CoreSummit/Model.xcdatamodeld/Model.xcdatamodel/contents, OpenStack Summit/CoreSummitTests/JSON/Summit6.json, OpenStack Summit/CoreSummitTests/JSON/Summit7.json, OpenStack Summit/CoreSummitTests/JSONTests.swift, OpenStack Summit/CoreSummitTests/StoreTests.swift, OpenStack Summit/OpenStack Summit/EventDetail.swift, OpenStack Summit/OpenStack Summit/EventViewController.swift
If true, then add event to attendee schedule before opening RSVP link.
=> [12524] Added `Event.externalRSVP`

OpenStack Summit/CoreSummit/Event.swift, OpenStack Summit/CoreSummit/EventDataUpdate.swift, OpenStack Summit/CoreSummit/EventDataUpdateJSON.swift, OpenStack Summit/CoreSummit/EventDataUpdateManagedObject.swift, OpenStack Summit/CoreSummit/EventJSON.swift, OpenStack Summit/CoreSummit/EventManagedObject.swift, OpenStack Summit/CoreSummit/MemberRequest.swift, OpenStack Summit/CoreSummit/Model.xcdatamodeld/Model.xcdatamodel/contents, OpenStack Summit/OpenStack Summit/Event.storyboard, OpenStack Summit/OpenStack Summit/EventDetail.swift, OpenStack Summit/OpenStack Summit/EventDetailViewController.swift, OpenStack Summit/OpenStack Summit/TableViewHeaderViewLight.xib
Added "Download Keynote" to Event Detail UI  and added `Event.attachment` in model.
=> [12707] Event Detail - Add "Download Keynote" link

OpenStack Summit/CoreSummit/FeedbackRequest.swift, OpenStack Summit/CoreSummit/Level.swift, OpenStack Summit/CoreSummit/Presentation.swift, OpenStack Summit/CoreSummit/PresentationDataUpdate.swift, OpenStack Summit/CoreSummit/PresentationDataUpdateJSON.swift, OpenStack Summit/OpenStack Summit.xcodeproj/project.pbxproj, OpenStack Summit/OpenStack Summit/AppDelegate.swift, OpenStack Summit/OpenStack Summit/AttendeeConfirmViewController.swift, OpenStack Summit/OpenStack Summit/Event.storyboard, OpenStack Summit/OpenStack Summit/EventDetailViewController.swift, OpenStack Summit/OpenStack Summit/EventViewController.swift, OpenStack Summit/OpenStack Summit/FavoriteEventsViewController.swift, OpenStack Summit/OpenStack Summit/Filter.swift, OpenStack Summit/OpenStack Summit/GeneralScheduleFilterViewController.swift, OpenStack Summit/OpenStack Summit/Info.plist, OpenStack Summit/OpenStack Summit/Member.storyboard, OpenStack Summit/OpenStack Summit/PersonalScheduleViewController.swift, OpenStack Summit/OpenStack Summit/PushNotificationManager.swift, OpenStack Summit/OpenStack Summit/ScheduleViewController.swift, OpenStack Summit/OpenStack Summit/SearchViewController.swift, OpenStack Summit/OpenStackSummitWatch Extension/Info.plist, OpenStack Summit/OpenStackSummitWatch/Info.plist
* dc0e426 [iOS] Fixed registering attendee with ticket code associated with multiple users.
* 885f81e [iOS] Fixed NOW alert not closing.
* 12c7fc6 [iOS] [12822] Fixes speaker search predicate.
* d7a906b [iOS] [12590] Fixes filters order.
* 9b5d61b [iOS] Makes watch later actions available to to-be-recorded events.
* 568a75e [iOS] Fixes schedule and watch list filtering bug.
* 558080c 92bab8a [iOS] Fixes local push notifications.
=> Release v2.3.2

OpenStack Summit/CoreSummit/CoreDataExtensions.swift, OpenStack Summit/OpenStack Summit/Menu.storyboard, OpenStack Summit/OpenStack Summit/NotificationDetailViewController.swift, OpenStack Summit/OpenStack Summit/Notifications.storyboard, OpenStack Summit/OpenStack Summit/PushNotificationManager.swift
User receives a message and the message counter on the Inbox button on the Menu will show the correct number of messages.
The user deletes one of the new (unread) messages but the message counter does not decrement.
The counter will decrement if the user reads the new message.
=> [iOS] [12864] Fixed invalid unread message count

OpenStack Summit/CoreSummit/DataUpdate.swift, OpenStack Summit/CoreSummit/Event.swift, OpenStack Summit/CoreSummit/EventDataUpdate.swift, OpenStack Summit/CoreSummit/EventDataUpdateJSON.swift, OpenStack Summit/CoreSummit/EventJSON.swift, OpenStack Summit/CoreSummit/EventManagedObject.swift, OpenStack Summit/CoreSummit/Link.swift, OpenStack Summit/CoreSummit/LinkJSON.swift, OpenStack Summit/CoreSummit/LinkManagedObject.swift, OpenStack Summit/CoreSummit/MemberRequest.swift, OpenStack Summit/CoreSummit/Model.xcdatamodeld/Model.xcdatamodel/contents, OpenStack Summit/CoreSummit/PresentationMaterial.swift, OpenStack Summit/CoreSummit/Slide.swift, OpenStack Summit/CoreSummit/SlideJSON.swift, OpenStack Summit/CoreSummit/SlideManagedObject.swift, OpenStack Summit/CoreSummit/Video.swift, OpenStack Summit/CoreSummit/VideoJSON.swift, OpenStack Summit/CoreSummit/VideoManagedObject.swift, OpenStack Summit/CoreSummitTests/JSON/DataUpdates13.json, OpenStack Summit/CoreSummitTests/JSON/DataUpdates14.json, OpenStack Summit/CoreSummitTests/JSON/DataUpdates15.json, OpenStack Summit/CoreSummitTests/JSON/DataUpdates16.json, OpenStack Summit/CoreSummitTests/JSONTests.swift, OpenStack Summit/OpenStack Summit.xcodeproj/project.pbxproj, OpenStack Summit/OpenStack Summit/EventDetail.swift
Fixes handling of Data updates for presentation materials.
=> [12866] Implement Data Updates for Presentation Materials

OpenStack Summit/CoreSummit/TrackGroupManagedObject.swift
2017-05-19 11:09:56.940 OpenStackSummit[18749:8775524] *** Terminating
app due to uncaught exception 'NSInvalidArgumentException', reason:
'Unsupported function expression count:(tracks.events)'
=> [CoreSummit] [12921] Fixed `NSPredicate` crash

OpenStack Summit/OpenStack Summit.xcodeproj/project.pbxproj, OpenStack Summit/OpenStack Summit/AboutViewController.swift, OpenStack Summit/OpenStack Summit/AppDelegate.swift, OpenStack Summit/OpenStack Summit/AppReview.swift, OpenStack Summit/OpenStack Summit/FeedbackViewController.swift, OpenStack Summit/OpenStack Summit/Preference.swift, OpenStack Summit/OpenStack Summit/ShowVideo.swift
We should [request app store reviews](https://blog.prototypr.io/whats-new-in-ios-10-3-for-product-designers-developers-1ca53d0c3905?gi=847e04483fd1) in the app.
We will prompt the user to review the app in the App Store  after certain events occur  (e.g. event rated, video finished playing, about screen loaded) and if the following requirements are met:
- Running iOS 10.3 or above
- App has been running for at least 5 minutes
- It's been a week since we last prompted the user for a review.
=> [iOS] [12800] Request App Store review

OpenStack Summit/CoreSummit/Attendee.swift, OpenStack Summit/CoreSummit/AttendeeJSON.swift, OpenStack Summit/CoreSummit/AttendeeManagedObject.swift, OpenStack Summit/CoreSummit/DataUpdate.swift, OpenStack Summit/CoreSummit/EventManagedObject.swift, OpenStack Summit/CoreSummit/EventScheduleRequest.swift, OpenStack Summit/CoreSummit/Member.swift, OpenStack Summit/CoreSummit/MemberJSON.swift, OpenStack Summit/CoreSummit/MemberManagedObject.swift, OpenStack Summit/CoreSummit/MemberRequest.swift, OpenStack Summit/CoreSummit/Model.xcdatamodeld/Model.xcdatamodel/contents, OpenStack Summit/CoreSummitTests/JSON/Member1.json, OpenStack Summit/CoreSummitTests/JSON/Member2.json, OpenStack Summit/CoreSummitTests/JSONTests.swift, OpenStack Summit/OpenStack Summit/EventDetailViewController.swift, OpenStack Summit/OpenStack Summit/EventViewController.swift, OpenStack Summit/OpenStack Summit/Member.storyboard, OpenStack Summit/OpenStack Summit/PersonalScheduleViewController.swift, OpenStack Summit/OpenStack Summit/PushNotificationManager.swift
Updates core summit and core data models and deserializers to consume new collection on json member.schedule_summit_events.
Updates UI logic to allow members access my schedule functionality.
=> [13091] [13092] Move schedule from attendee to member
